### PR TITLE
Import missing formulas from homebrew-science

### PR DESCRIPTION
**Pull request by andrewyatz**
As detailed in issue #15 these are all the missing dependencies. Also had to revert a number of commits from @muffato as the formula had appeared in homebrew-science but now that's dead we need them back in here.

### CODE REVIEW

**Comment by muffato** [comment]
Like you said on Slack, some formulae are missing. Are you going to add them @andrewyatz or would I do it ?

I've had a first look at the commits and the formulae are mostly ok. I still need to assess the differences between your version and the one in homebrew-science (prior to closure) for `biopp`, `fasttree`, `libpll`, `phyldog`, `prank`

**Comment by muffato** [comment]
`fasttree` ok

**Comment by muffato** [comment]
`phyldog` ok

**Comment by thibauthourlier** [comment]
I have patched `cesar`, `crossmap`, `repeatmasker` but I'm waiting for my linuxbrew to be ready to test the patches. I also half patched `exonerate22` and `exonerate24`

**Comment by muffato** [comment]
`libpll` ok too, although I don't understand why our SHA256 checksum is different from the one homebrew-science used to have :thinking:

**Comment by thibauthourlier** [comment]
`exonerate22` and `exonerate24` checked

**Comment by muffato** [comment]
Found some issues when building on Docker:

## lp_solve
```
==> Downloading https://downloads.sourceforge.net/lpsolve/lp_solve_5.5.2.0_source.tar.gz
==> Downloading from https://downloads.sourceforge.net/project/lpsolve/lpsolve/5.5.2.0/lp_solve_5.5.2.0_source.tar.gz
######################################################################## 100.0%
==> sh ccc # lpsolve55 library
Warning: tried to install empty array to /home/linuxbrew/.linuxbrew/Cellar/lp_solve/5.5.2.0/lib
Warning: tried to install empty array to /home/linuxbrew/.linuxbrew/Cellar/lp_solve/5.5.2.0/lib
==> sh ccc # lp_solve executable
Last 15 lines from /home/linuxbrew/.cache/Homebrew/Logs/lp_solve/02.sh:
../lp_lib.h:63:0: warning: "isnan" redefined
 # define isnan(x) FALSE
 ^
In file included from lp_solve.c:4:0:
/usr/include/math.h:292:0: note: this is the location of the previous definition
 #  define isnan(x) __builtin_isnan (x)
 ^
In file included from ../lp_SOS.c:3:0:
../shared/commonlib.h:88:24: error: expected identifier or '(' before numeric constant
   #define FALSE        0
                        ^
In file included from ../lp_utils.c:4:0:
../shared/commonlib.h:88:24: error: expected identifier or '(' before numeric constant
   #define FALSE        0
                        ^
```

## newick-utils
```
==> Downloading http://cegg.unige.ch/pub/newick-utils-1.6.tar.gz
######################################################################## 100.0%
==> Patching
patching file tests/test_nw_gen.sh
patch unexpectedly ends in middle of line
Error: Failure while executing: patch -g 0 -f -p1
```

## repeatscout
```
Error: No available formula with the name "ensembl/ensembl/trf" (dependency of repeatscout)
==> Searching for a previously deleted formula...
Warning: ensembl/ensembl is shallow clone. To get complete history run:
  git -C "$(brew --repo ensembl/ensembl)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
Error: No similarly named formulae found.
```

**Comment by muffato** [comment]
`newick-utils` fixed but I still have an intermittent error when doing `make check`

**Comment by muffato** [comment]
I've found two more errors

## tophat
```
Error: No available formula with the name "bowtie" (dependency of tophat)
==> Searching for a previously deleted formula...
Warning: homebrew/core is shallow clone. To get complete history run:
  git -C "$(brew --repo homebrew/core)" fetch --unshallow

Error: No previously deleted formula found.
==> Searching for similarly named formulae...
==> Searching local taps...
This similarly named formula was found:
bowtie2
To install it, run:
  brew install bowtie2
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

## trf
```
==> Downloading https://tandem.bu.edu/trf/downloads/trf409.linux64

curl: (60) SSL certificate problem: certificate has expired
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
Error: Failed to download resource "trf"
Download failed: https://tandem.bu.edu/trf/downloads/trf409.linux64
```
Hopefully a transient error

**Comment by muffato** [comment]
I will try `lp_solve` again later on an ebi machine

**Comment by muffato** [comment]
`newick-utils` completely fixed

**Comment by muffato** [comment]
`lp_solve` still doesn't work. I think it doesn't like recent versions of gcc :/
* http://lp-solve.2324885.n4.nabble.com/Error-when-compiling-lpsolve-on-Linux-tc10258.html
* http://lp-solve.2324885.n4.nabble.com/LpSolve-compilation-error-with-gcc-6-2-1-and-some-modifications-for-MacOS-td10390.html

**Comment by andrewyatz** [comment]
Okay wiggletools now in external and approval met 👍 . Integration will now happen

**Pull request merged**
